#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import from the standard library
from os.path import split
import argparse
import pandas as pd

# Import from awesomepkg
import awesomepkg
from awesomepkg.lib import try_me

if __name__ == '__main__':
    usage = '%(prog)s'
    description = 'awesomepkg_description'
    # https://docs.python.org/3/library/argparse.html
    # https://docs.python.org/3/howto/argparse.html
    parser = argparse.ArgumentParser(description=description, usage=usage)
    args = parser.parse_args()
    try_me()
